# Generated by Django 5.2.5 on 2025-08-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="file",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AddField(
            model_name="file",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="%(class)s/avatar/",
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="%(class)s/avatar/",
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_enable",
            field=models.BooleanField(default=True, verbose_name="is enable"),
        ),
        migrations.AlterField(
            model_name="file",
            name="is_enable",
            field=models.BooleanField(default=True, verbose_name="is enable"),
        ),
        migrations.AlterField(
            model_name="product",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="%(class)s/avatar/",
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_enable",
            field=models.BooleanField(default=True, verbose_name="is enable"),
        ),
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
        migrations.AlterModelTable(
            name="file",
            table=None,
        ),
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
    ]
