# Generated by Django 5.2.5 on 2025-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_options_alter_file_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_stock",
            field=models.BooleanField(default=True, verbose_name="in stock?"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0, verbose_name="price"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stars",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="start count"
            ),
        ),
    ]
