# Generated by Django 5.2.5 on 2025-09-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_is_new_product_is_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="off_price_persent",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
