# Generated by Django 5.2.5 on 2025-09-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_off_price_persent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="off_price_persent",
        ),
        migrations.AddField(
            model_name="product",
            name="off_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="off price"
            ),
        ),
    ]
