# Generated by Django 5.2.5 on 2025-09-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_off_price_persent_product_off_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "File", "verbose_name_plural": "Files"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="is new product?"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_off",
            field=models.BooleanField(default=False, verbose_name="product have off?"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stars",
            field=models.IntegerField(blank=True, default=0, verbose_name="star count"),
        ),
    ]
