# Generated by Django 5.2.5 on 2025-09-07 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0008_cart_contact_customer_cartitem_comment_cart_customer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 9, 7, 14, 41, 37, 746404, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
