# Generated by Django 5.2.5 on 2025-09-09 08:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 9, 9, 8, 33, 13, 287197, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
