# Generated by Django 5.2.5 on 2025-09-09 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_file_product_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 9, 9, 11, 7, 32, 380635, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
