# Generated by Django 5.2.5 on 2025-09-09 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_file_description_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 9, 9, 21, 37, 59, 534979, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
