# Generated by Django 5.2.5 on 2025-09-09 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 9, 9, 21, 38, 27, 5318, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
