# Generated by Django 5.2.5 on 2025-09-09 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="files/avatar/", verbose_name="avatar"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="files/avatar/", verbose_name="avatar"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 9, 9, 22, 6, 27, 216900, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="files/avatar/", verbose_name="avatar"
            ),
        ),
    ]
